[package]
name = "youdao_rs"
version = "0.1.0"
authors = ["wangchi <addictedtoelixir@gmail.com>"]

[dependencies]
ansi_term = "0.10"
scraper = "0.7.0"
reqwest = "0.8.6"
percent-encoding = "1.0.1"
itertools = "0.7.8"
tempfile = "3.0.3"
failure = "0.1.2"